//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IEnumerableVsIQueryable
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROJECT_TEAM
    {
        public string PRJ_ID { get; set; }
        public string FRST_NM { get; set; }
        public string LAST_NM { get; set; }
    }
}
